stages:
  - build
  - test

job_build1:
  stage: build
  script:
    - python3 -c "import os; print(os.getcwd())"

job_build2:
  stage: build
  script:
    - python3 -c "import os; print(os.getcwd())"

job_test:
  stage: test
  script:
    -  pwd
  when: manual
  needs:
    - job: job_build1
      optional: true
    - job: job_build2
      optional: true
